package com.athletix.enums;

public enum SportEnum {
    RUNNING, CYCLING, SWIMMING, HIKING, WALKING, SKATING, SKIING, SNOWBOARDING, CLIMBING, MOUNTAIN_BIKING,
    TRIATHLON, MARATHON, IRONMAN, ULTRAMARATHON, TRAIL_RUNNING, ROAD_RUNNING, CROSS_COUNTRY_RUNNING
}
